backend:
  # name: test-repo # 測試專用 https://www.netlifycms.org/docs/test-backend/
  name: git-gateway # https://www.netlifycms.org/docs/git-gateway-backend/
  branch: main # 要更新的分支(可選；默認為主分支)
  squash_merges: true # 合併提交

local_backend: true

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "source/images/uploads" # 媒體文件將存儲在圖片/上載下的Repo中。
public_folder: "/images/uploads" # 上傳的媒體的src屬性將以/images/uploads開頭。

locale: "zh_Hans" # 語言環境 https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-locales/src

collections:      # https://www.netlifycms.org/docs/configuration-options/#collections
  - name: "posts" # 在路由中使用，例如：/admin/collections/blog。
    label: "Post" # 在用戶界面中使用
    folder: "source/_posts" # 存儲文件的文件夾的路徑。
    create: true # 允許用戶在這個集合中創建新的文件。
    fields: # 每份文件的字段，通常是前面的內容。
      - {label: "頂部圖", name: "banner_img", widget: "image", required: false} 
      - {label: "文章封面", name: "index_img", widget: "image", required: false} 
      - {label: "文章排序", name: "sticky", widget: "number", required: false}
      - {label: "標題", name: "title", widget: "string"}
      - {label: "發佈日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", required: false}
      - {label: "更新日期", name: "updated", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", dateFormat: "YYYY-MM-DD", timeFormat: "HH:mm:ss", required: false}
      - {label: "標籤", name: "tags", widget: "list", required: false}
      - {label: "分類", name: "categories", widget: "list", required: false}
      - {label: "關鍵詞", name: "keywords", widget: "list", required: false}
      - {label: "摘要", name: "excerpt", widget: "list", required: false}
      - {label: "內容", name: "body", widget: "markdown", required: false}
      - {label: "永久鏈接", name: "permalink", widget: "string", required: false}
      - {label: "評論", name: "comments", widget: "boolean", default: true, required: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "source/about/index.md"
        name: "about"
        label: "關於"
        fields:
          - {label: "標題", name: "title", widget: "string"}
          - {label: "內容", name: "body", widget: "markdown", required: false}
          - {label: "評論", name: "comments", widget: "boolean", default: true, required: false}

  - name: "settings"
    label: "settings"
    files:      
      - file: "source/_data/fluid_config.yml"
        name: "fluid"
        label: "fluid主題配置"
        editor:
          preview: true      # 是否開啓編輯預覽
        fields:
          - label: "首頁"
            name: "index"
            widget: "object"
            collapsed: true   # 是否折疊顯示
            fields:
              - label: "頂部圖"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number"
          - label: "文章頁"
            name: "post"
            widget: "object"
            collapsed: true
            fields:
              - label: "頂部圖(默認)"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number" 
              - label: "文章封面圖(默認)"
                name: "default_index_img"
                widget: "image"
          - label: "歸檔頁"
            name: "archive"
            widget: "object"
            collapsed: true
            fields:
              - label: "頂部圖"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number"
          - label: "分類頁"
            name: "category"
            widget: "object"
            collapsed: true
            fields:
              - label: "頂部圖"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number"
          - label: "標籤頁"
            name: "tag"
            widget: "object"
            collapsed: true
            fields:
              - label: "頂部圖"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number"
          - label: "關於頁"
            name: "about"
            widget: "object"
            collapsed: true
            fields:
              - label: "頂部圖"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number"
          - label: "友鏈頁面"
            name: "links"
            widget: "object"
            collapsed: true
            fields:
              - label: "頂部圖"
                name: "banner_img"
                widget: "image"
              - label: "高度"
                name: "banner_img_height"
                widget: "number"
              - label: "項目"
                name: "items"
                widget: "list"
                fields:
                  - {label: "網站名稱", name: "title", widget: "string", required: false}
                  - {label: "網址描述", name: "intro", widget: "string", required: false}
                  - {label: "網站地址", name: "link", widget: "string", required: false}
                  - {label: "網站圖片", name: "avatar", widget: "image", required: false}
