index:
  banner_img: https://raw.githubusercontent.com/camellusforest/Image/master/imgs/20200812021945.jpg
  banner_img_height: 100
post:
  banner_img: https://raw.githubusercontent.com/camellusforest/Image/master/imgs/20200812021945.jpg
  banner_img_height: 70
  default_index_img: https://raw.githubusercontent.com/camellusforest/Image/master/imgs/20200921053604.jpg
archive:
  banner_img: /images/uploads/1616421595370-wallhaven-q6ov7d.jpg
  banner_img_height: 80
category:
  banner_img: /images/uploads/1616421818281-wallhaven-zm93dj.jpg
  banner_img_height: 80
tag:
  banner_img: /images/uploads/1616421669417-wallhaven-1kkm2g.jpg
  banner_img_height: 80
about:
  banner_img: /images/uploads/wallhaven-pkkr2.webp
  banner_img_height: 80
links:
  items: []
  banner_img_height: 0
  banner_img: https://raw.githubusercontent.com/camellusforest/Image/master/imgs/20211109164910.jpg
