index:
  banner_img: https://raw.githubusercontent.com/camellusforest/Image/master/imgs/20211109164910.jpg
  banner_img_height: 100
post:
  banner_img: https://raw.githubusercontent.com/camellusforest/Image/master/imgs/20200918132922.jpg
  banner_img_height: 70
  default_index_img: https://raw.githubusercontent.com/camellusforest/Image/master/imgs/20200812015548.jpg
archive:
  banner_img: https://raw.githubusercontent.com/camellusforest/Image/master/imgs/20200917130306.jpg
  banner_img_height: 80
category:
  banner_img: https://raw.githubusercontent.com/camellusforest/Image/master/imgs/20200830160826.jpg
  banner_img_height: 80
tag:
  banner_img: https://raw.githubusercontent.com/camellusforest/Image/master/imgs/20211109202326.jpg
  banner_img_height: 80
about:
  banner_img: https://raw.githubusercontent.com/camellusforest/Image/master/imgs/20211109202803.jpg
  banner_img_height: 80
links:
  items: []
  banner_img_height: 0
  banner_img: https://raw.githubusercontent.com/camellusforest/Image/master/imgs/20211109164910.jpg
